blog/Login/urls.py
from Login import views
from django.conf.urls import url

app_name = '[Login]'
urlpatterns = [
    url(r'^$', views.loginPage),
    url(r'^home/', views.homePage, name="home"),
    url(r'^login/', views.login, name="toLogin"),
    url(r'^retrievePassword/', views.retrievePassword, name="retrievePassword"),
    url(r'^register/', views.register, name="register"),
    url(r'^changePassword/', views.changePassword, name="changePassword"),
    url(r'^newPassage/', views.newPassage, name="newPassage"),
    url(r'^passage/(?P<passage_id>\d+)$', views.passagePage, name="passage"),
    url(r'^editPassage/(?P<passage_id>\d+)$', views.editPassage, name="editPassage"),
    url(r'^$', views.Logoff, name="Logoff"),
    url(r'^passage/(?P<passage_id>\d+)/reply$', views.replies, name="replies"),
]

blog/blog/urls.py
from django.contrib import admin
from django.contrib import admin
from Login import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.loginPage),
    url(r'^Login/', include("Login.urls", namespace="Login_up")),
]

blog/templates/changePassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>找回密码</title>
</head>
<body>
    <form action="{% url "Login_up:changePassword" %}" method="post">
        {% csrf_token %}
        <a href="/Login/">返回首页</a> <br />
        账号: <input type="text" name="userName"  value="{{ userName }}" /><br />
        密保问题： <input type="text" name="question" value="{{ question }}" /><br />
        密保答案: <input type="text" name="answer" value="{{ answer }}"  /><br />
        新密码：<input type="password" name="newPassword"  /><br />
        确认密码：<input type="password" name="confirmPassword"  /><br />

                <input type="submit" value="完成" name="changePassword" /><br />
        {{ result }}
</body>
</html>

blog/templates/editPassage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑</title>
</head>
<body>
<a href="/Login/home">返回主页</a> <br />
<form action="{% url "Login_up:editPassage" passage.id%}" method="post">
      <label>
         文章标题
         <input type="text" name="title" value="{{ passage.title }}"/>
     </label>
     <br>
     <label>
         文章内容
         <input type="text" name="content" value="{{ passage.content }}" style="height: 50px;width: 50px"/>
     </label>
     <br>
     <input type="submit" value="完成" name="finish">
    {{ result }}
    </form>
</body>
</html>

blog/templates/homePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
</head>
<body>

    <form action="{% url "Login_up:toLogin" %}" method="post">
        {% csrf_token %}
        账号: <input type="text" name="userName" value="{{ userName }}"/>
        <a href="../Login/register/">注册账号</a><br />


        密码: <input type="password" name="password" />
        <a href="../Login/retrievePassword/">找回密码</a> <br />

        <input type="submit" value="登陆" name="Login" />
        <a href="../Login/changePassword/">修改密码</a> <br />
        {{ result }}

    </form>

</body>
</html>

blog/templates/newPassage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新文章</title>
</head>
<a href="/Login/home">返回主页</a> <br />
<form action="{% url "Login_up:newPassage" %}" method="post">
      <label>
         文章标题
         <input type="text" name="title"/>
     </label>
     <br>
     <label>
         文章内容
         <input type="text" name="content" style="height: 50px;width: 50px"/>
     </label>
     <br>
     <input type="submit" value="提交" name="submit">
    {{ result }}
 </form>
</body>
</html>

blog/templates/passage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章</title>
</head>
<body>
<a href="/Login/home">返回主页</a> <br />
<form action="{% url "Login_up:passage" passage.id %}" method="post">
        <p>作者:{{ passage.author.userName }} 发表时间：{{ passage.creationTime }} 修改时间：{{ passage.changeTime }}</p>
    <br/>
          <p>标题:{{ passage.title }}</p><br/>
      <br/>
          <p>内容:{{ passage.content }}</p>
      <br/>
    <input type="submit" value="修改" name="edit"><input type="submit" value="删除" name="delete"><br />
 </form>




<div>
    <form action="{% url "Login_up:replies" passage.id %}" method="post">
    <input type="text" name="replies">
        <input type="submit" value="回复" name="reply"><br>
    </form>
        {% for replies in allReplies %}
       <p>{{ replies.author.userName }}:{{ replies.content }}--{{ replies.replyTime }}</p><br>
    {% endfor %}


</div>

</body>
</html>

blog/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    <form action="{% url "Login_up:register" %}" method="post">
        {% csrf_token %}
        <a href="/Login/">返回首页</a> <br />
        账号: <input type="text" name="userName"  /><br />
        个人介绍: <input type="text" name="describe"  /><br />
        密码: <input type="password" name="password" /><br />
        确认密码：<input type="password" name="confirmPassword"  /><br />
        密保问题: <input type="text" name="question"  /><br />
        密保答案: <input type="text" name="answer"  /><br />

         <input type="submit" value="注册" name="register"/>
        {{ result }}

    </form>

</body>
</html>

blog/templates/retrievePassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>找回密码</title>
</head>
<body>
    <form action="{% url "Login_up:retrievePassword" %}" method="post">
        {% csrf_token %}
        <a href="/Login/">返回首页</a> <br />
        账号: <input type="text" name="userName"  value="{{ userName }}" /><br />
        密保问题： <input type="text" name="question" value="{{ question }}" /><br />
        密保答案: <input type="text" name="answer" value="{{ answer }}"  /><br />

                <input type="submit" value="完成" name="retrievePassword" /><br />
        {{ result }}

    </form>

</body>
</html>

blog/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>成功</title>
</head>
<body>
<a href="/Login/home">返回主页</a> <br />
<p>成功</p>
</body>
</html>

blog/templates/userPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
</head>
<body>
<p>welcome {{ userName }}</p><br />
<form action="{% url "Login_up:Logoff"%}">
<input type="submit"  value="注销" name="Logoff"/><br />
</form>
 <a href="/Login/newPassage">新文章</a>
<br />
<p>----------------------------------------------------------------------------------------------------</p><br />
    {% for passage in passages%}
        <a href="{% url 'Login_up:passage' passage.id %}">{{ passage.title }}</a><br />
        作者：{{ passage.author.userName }}<br>
       <br/>
    {% endfor %}
</body>
</html>